#!/usr/bin/env Rscript
source(file.path(dirname(sub("^--file=","",commandArgs(FALSE)[grepl("^--file=",commandArgs(FALSE))])),"common.R"))
fc<-file.path(tempdir(),'font_cache');dir.create(fc,showWarnings=FALSE);Sys.setenv(XDG_CACHE_HOME=fc)
suppressPackageStartupMessages({library(ggplot2);library(patchwork);library(stringr)})
stopifnot(all(fread(file.path(out,'results/tables/03_verification_checks.csv'))$pass))
hi<-'#BC496B';lo<-'#327F94';ink<-'#223543';gray<-'#65737D';pal<-c('#D3E6EA','#62A7BA','#286886','#182E52')
fmt<-function(x)ifelse(is.na(x),'NE',ifelse(x<.001,formatC(x,format='e',digits=1),formatC(x,format='f',digits=3)))
base<-theme_classic(base_size=11,base_family='Arial')+theme(axis.text=element_text(colour=ink),axis.title=element_text(colour=ink),plot.title=element_text(face='bold',colour=ink,size=15),plot.subtitle=element_text(size=10.5,colour=gray,lineheight=1.15),plot.caption=element_text(size=9,colour=gray,hjust=0,lineheight=1.2),legend.position='bottom',legend.title=element_text(size=10,margin=margin(r=7)),legend.text=element_text(size=9.5),plot.margin=margin(10,15,10,10))
ann<-theme(plot.title=element_text(family='Arial',face='bold',size=17,colour=ink),plot.subtitle=element_text(family='Arial',size=11,colour=gray,margin=margin(t=5,b=8)),plot.caption=element_text(family='Arial',size=9,colour=gray,hjust=0,lineheight=1.15,margin=margin(t=8)),plot.margin=margin(14,16,12,16))
savefig<-function(p,n,w,h){ggsave(file.path(out,'results/figures',paste0(n,'.png')),p,width=w,height=h,dpi=600,device=ragg::agg_png,bg='white');ggsave(file.path(out,'results/figures',paste0(n,'.pdf')),p,width=w,height=h,device=cairo_pdf,bg='white');ggsave(file.path(out,'results/figures',paste0(n,'.svg')),p,width=w,height=h,device=grDevices::svg,bg='white');cat('SAVED',n,w,h,'\n')}
label<-function(x){s<-str_to_sentence(gsub('_',' ',sub('^GOBP_','',x)));s<-gsub('\\bdna\\b','DNA',s,ignore.case=TRUE);s<-gsub('\\brna\\b','RNA',s,ignore.case=TRUE);s<-gsub('\\bmrna\\b','mRNA',s,ignore.case=TRUE);s<-gsub('\\brrna\\b','rRNA',s,ignore.case=TRUE);s<-gsub('\\bb cell\\b','B cell',s,ignore.case=TRUE);s<-gsub('\\bpoly a\\b','poly(A)',s,ignore.case=TRUE);str_wrap(s,width=34)}

d<-fread(file.path(out,'results/tables/plotdata_GO_overview.csv'));d[,':='(display_label=label(pathway),neglog10q=-log10(q_global_cDC),absNES=abs(NES),display_y=9-display_order)]
d[pathway=='GOBP_ANTIMICROBIAL_HUMORAL_IMMUNE_RESPONSE_MEDIATED_BY_ANTIMICROBIAL_PEPTIDE',display_label:='Antimicrobial peptide-mediated\nhumoral immune response']
d[pathway=='GOBP_ATP_BIOSYNTHETIC_PROCESS',display_label:='ATP biosynthetic process']
d[pathway=='GOBP_DISRUPTION_OF_ANATOMICAL_STRUCTURE_IN_ANOTHER_ORGANISM',display_label:="Disruption of another organism's\nanatomical structure"]
qmax<-if(nrow(d))ceiling(max(d$neglog10q))else 1;xmax<-if(nrow(d))ceiling(max(d$absNES)*2)/2+.15 else 3
sb<-if(nrow(d))unique(pmax(1,round(seq(min(d$leading_edge_n),max(d$leading_edge_n),length.out=3))))else 1;sizelim<-c(0,if(nrow(d))max(d$leading_edge_n)else 1)
parts<-lapply(c('High','Low'),function(dr){dd<-copy(d[direction==dr]);setorder(dd,display_order);col<-if(dr=='High')hi else lo
 if(!nrow(dd))return(ggplot()+annotate('text',x=0,y=0,label='No GO:BP terms meet\ncDC-wide BH q < 0.05',family='Arial',colour=gray,size=4)+theme_void()+labs(title=paste0('Degradation-',dr)))
 p<-ggplot(dd,aes(x=absNES,y=display_y))+geom_segment(aes(x=0,xend=absNES,yend=display_y),colour='#DCE5EB',linewidth=.6)+geom_point(aes(fill=neglog10q,size=leading_edge_n),shape=21,colour='white',stroke=.45)+scale_y_continuous(breaks=dd$display_y,labels=dd$display_label,limits=c(.4,8.65),expand=expansion(mult=0))+scale_x_continuous(limits=c(0,xmax),breaks=seq(0,floor(xmax),1),expand=expansion(mult=c(0,.04)))+scale_fill_gradientn(colours=pal,limits=c(0,qmax),name='−log10(cDC-wide BH q)',guide=guide_colorbar(order=1,barwidth=unit(35,'mm'),barheight=unit(2.5,'mm')))+scale_size_area(max_size=6,limits=sizelim,breaks=sb,name='Leading-edge genes',guide=guide_legend(order=2,override.aes=list(fill='#608A9F',colour='white')))+labs(title=paste0('Degradation-',dr),subtitle=if(dr=='High')'Enriched toward higher degradation expression'else'Enriched toward lower degradation expression',x='Enrichment strength |NES|',y=NULL)+base+theme(axis.line.y=element_blank(),axis.ticks.y=element_blank(),axis.text.y=element_text(size=10.5,lineheight=1.03,margin=margin(r=9)),axis.line.x=element_line(colour='#9FAAB1',linewidth=.35),axis.ticks.x=element_line(colour='#9FAAB1'),plot.title=element_text(colour=col,size=15),legend.margin=margin(4,6,4,6))
 if(nrow(dd)<8)p<-p+annotate('text',x=xmax/2,y=.95,label=paste0(nrow(dd),' terms retained after\ngene-overlap filtering'),family='Arial',colour=gray,size=3.4)
 p
})
p<-(parts[[1]]|parts[[2]])+plot_layout(guides='collect')+plot_annotation(title='Conventional DC pathways by tumour sarcosine-degradation expression',subtitle='Fixed whole-tumour groups  |  Post-treatment NSCLC  |  High n = 5, Low n = 3  |  772 conventional DCs',caption='Patient-level pseudobulk; histology-adjusted GSEA; BH across all 3,797 tested gene sets in this cDC analysis.\nExploratory: 8 patients with ≥50 cDCs each. Up to eight significant GO:BP terms per direction, with gene-overlap filtering.',theme=ann)&theme(legend.position='bottom')
savefig(p,'cDC_GO_Overview',12.4,7.1)
wt(d,'plotdata_GO_display.csv')
e<-fread(file.path(out,'results/tables/plotdata_Exact_Fig7_Pathways.csv'));e[,':='(display_y=5-display_order,point_fill=ifelse(significant,ifelse(NES>0,hi,lo),'white'),point_line=ifelse(NES>0,hi,lo))]
lab4<-c('APC cross-presentation','TCR signaling','TNFR2-related\nnoncanonical NF-κB','IFN-γ response')
p<-ggplot(e,aes(NES,display_y))+geom_vline(xintercept=0,colour='#ACB8C0',linewidth=.4,linetype='dashed')+geom_segment(aes(x=0,xend=NES,yend=display_y),colour='#D6E0E6',linewidth=.8)+geom_point(aes(fill=point_fill,colour=point_line),shape=21,size=4.4,stroke=.9)+scale_fill_identity()+scale_colour_identity()+geom_text(aes(x=2.27,label=q_label),hjust=0,family='Arial',colour=ink,size=3.65)+annotate('text',x=2.27,y=4.68,label='BH q',hjust=0,family='Arial',colour=gray,size=3.3)+scale_y_continuous(breaks=4:1,labels=lab4,limits=c(.55,4.92),expand=expansion(mult=0))+scale_x_continuous(breaks=-2:2,expand=expansion(mult=0))+coord_cartesian(xlim=c(-2,2),clip='off')+labs(title='Four immune programs in conventional DCs',subtitle='Whole-tumour Degradation groups  |  Post-treatment NSCLC\nHigh n = 5, Low n = 3  |  772 conventional DCs',x='NES (High − Low)',y=NULL,caption='Patient-level pseudobulk; histology-adjusted GSEA. Positive NES: Degradation-High.\nFilled points: cDC-wide BH q < 0.05; open points: q ≥ 0.05.\nBH across all 3,797 tested gene sets; exploratory analysis of 8 patients.')+base+theme(axis.line.y=element_blank(),axis.ticks.y=element_blank(),axis.text.y=element_text(size=11,margin=margin(r=8)),plot.title=element_text(size=16),plot.subtitle=element_text(size=10.5,margin=margin(t=5,b=10)),plot.caption=element_text(size=8.4,margin=margin(t=14)),plot.caption.position='plot',plot.title.position='plot',plot.margin=margin(15,86,13,16))
savefig(p,'cDC_Exact_Immune_Pathways',8.8,5.7)
wt(e,'plotdata_Exact_display.csv');capture.output(sessionInfo(),file=file.path(out,'logs/sessionInfo_plot.txt'))
