#!/usr/bin/env Rscript

# Independent numerical and file-integrity verification for the pooled
# Production/Degradation heatmap generated by script 115.

suppressPackageStartupMessages({
  library(dplyr)
})

options(stringsAsFactors = FALSE, scipen = 999)

script_arg <- commandArgs(trailingOnly = FALSE)
script_file <- sub("^--file=", "", script_arg[grepl("^--file=", script_arg)])
if (length(script_file) != 1L) stop("Run with Rscript.")

integrated_root <- normalizePath(file.path(dirname(script_file), ".."), mustWork = TRUE)
crc_root <- normalizePath(file.path(integrated_root, ".."), mustWork = TRUE)
project_root <- normalizePath(file.path(integrated_root, "..", "..", ".."), mustWork = TRUE)
use_root <- file.path(crc_root, "사용데이터_모음")
out_dir <- file.path(
  integrated_root,
  "results_integrated",
  "CRC_WGS_PROD_DEG_POOLED_HEATMAP_26.09.01"
)
use_out_dir <- file.path(use_root, "CRC_WGS_ProdDeg_PooledHeatmap_26.09.01")

cohorts <- c("PRJEB10878", "PRJEB27928", "PRJEB6070", "PRJNA429097")
score_file <- file.path(
  use_root,
  "Derived_Sarcosine_Functional_Scores",
  "CRC_WGS_sarcosine_functional_scores_all_cohorts.csv"
)
species_files <- setNames(
  file.path(
    use_root,
    cohorts,
    paste0(cohorts, "_species_relative_abundance_matrix.csv")
  ),
  cohorts
)
cancer_file <- file.path(
  integrated_root,
  "results_integrated",
  "cross_cohort",
  "cross_cohort_CRC_enriched_membership_matrix.csv"
)
healthy_file <- file.path(
  integrated_root,
  "results_integrated",
  "SupFig3de_HEALTHY_ENRICHED_26.08.27",
  "healthy_enriched_membership_matrix.csv"
)

cor_file <- file.path(
  out_dir,
  "pooled_species_Production_Degradation_correlations_all.csv"
)
prev_file <- file.path(out_dir, "pooled_species_prevalence.csv")
top_file <- file.path(out_dir, "selected_top15_per_axis.csv")
plot_file <- file.path(out_dir, "heatmap_plot_values_long.csv")
overlap_file <- file.path(out_dir, "selected_species_disease_enrichment_overlap.csv")
taxonomy_file <- file.path(out_dir, "selected_species_taxonomy_map.csv")
sample_file <- file.path(out_dir, "pooled_sample_scores_selected_species.csv")
count_file <- file.path(out_dir, "sample_counts_by_cohort_group.csv")
input_all_file <- file.path(out_dir, "pooled_analysis_input_all_union_species.csv")
input_filtered_file <- file.path(out_dir, "pooled_analysis_input_prevalence10_species.csv")
png_file <- file.path(
  out_dir,
  "Fig_CRC_WGS_species_Production_Degradation_POOLED_heatmap.png"
)

manuscript_candidates <- list.dirs(project_root, recursive = FALSE, full.names = TRUE)
manuscript_candidates <- manuscript_candidates[
  grepl("^Manuscript", basename(manuscript_candidates))
]
if (length(manuscript_candidates) != 1L) stop("Could not resolve Manuscript directory.")
transport_file <- file.path(
  manuscript_candidates,
  "FigDesign&Manuscript",
  "PPT_INSERT_CRC_WGS_ProdDeg_POOLED_Heatmap.png"
)

checks <- character()
failures <- character()
check <- function(ok, label) {
  if (isTRUE(ok)) {
    checks <<- c(checks, paste("PASS", label, sep = "\t"))
  } else {
    failures <<- c(failures, paste("FAIL", label, sep = "\t"))
  }
}

required <- c(
  score_file, unname(species_files), cancer_file, healthy_file,
  cor_file, prev_file, top_file, plot_file, overlap_file,
  taxonomy_file, sample_file, count_file, input_all_file,
  input_filtered_file, png_file, transport_file
)
check(all(file.exists(required)), "all required inputs and outputs exist")
if (!all(file.exists(required))) {
  report <- c(checks, failures, "TOTAL_FAIL\t1")
  writeLines(report, file.path(out_dir, "independent_verification_report.txt"))
  stop("Missing required verification files.")
}

scores <- read.csv(score_file, check.names = FALSE) |>
  select(Run_ID, Cohort, Analysis_Group, Production_sum, Degradation_sum) |>
  arrange(match(Cohort, cohorts), Run_ID)
check(nrow(scores) == 1647L, "score table contains 1,647 pooled Run IDs")
check(!anyDuplicated(scores$Run_ID), "pooled Run IDs are unique")

tables <- list()
union_taxa <- character()
for (cohort in cohorts) {
  dat <- read.csv(species_files[[cohort]], check.names = FALSE)
  ids <- scores$Run_ID[scores$Cohort == cohort]
  dat <- dat[match(ids, dat$Run_ID), , drop = FALSE]
  check(identical(dat$Run_ID, ids), paste0(cohort, " species rows match score Run IDs"))
  tables[[cohort]] <- dat
  union_taxa <- union(union_taxa, colnames(dat)[-1])
}

pooled <- matrix(
  0,
  nrow = nrow(scores),
  ncol = length(union_taxa),
  dimnames = list(scores$Run_ID, union_taxa)
)
for (cohort in cohorts) {
  dat <- tables[[cohort]]
  vals <- as.matrix(dat[, -1, drop = FALSE])
  storage.mode(vals) <- "double"
  pooled[dat$Run_ID, colnames(dat)[-1]] <- vals
}
check(nrow(pooled) == 1647L, "independent pooled species matrix has 1,647 rows")
check(all(is.finite(pooled)) && all(pooled >= 0), "pooled species matrix is finite and non-negative")

input_all_saved <- read.csv(input_all_file, check.names = FALSE)
check(
  nrow(input_all_saved) == 1647L &&
    ncol(input_all_saved) == 5L + ncol(pooled) &&
    identical(input_all_saved$Run_ID, scores$Run_ID) &&
    identical(colnames(input_all_saved)[-(1:5)], colnames(pooled)),
  "all-union pooled input preserves 1,647 Run IDs and every union species column"
)
check(
  max(abs(as.matrix(input_all_saved[, -(1:5), drop = FALSE]) - pooled)) < 1e-15 &&
    isTRUE(all.equal(
      input_all_saved[, 1:5], scores,
      tolerance = 1e-15, check.attributes = FALSE
    )),
  "all-union pooled input preserves all scores and species abundances"
)

prev_saved <- read.csv(prev_file, check.names = FALSE)
prev_recalc <- colMeans(pooled > 0)
prev_match <- prev_saved$n_detected == colSums(pooled[, prev_saved$Species_full, drop = FALSE] > 0) &
  abs(prev_saved$prevalence - prev_recalc[prev_saved$Species_full]) < 1e-15 &
  prev_saved$pass_prevalence_10pct == (prev_recalc[prev_saved$Species_full] >= 0.10)
check(all(prev_match), "all pooled prevalence values and filter flags independently match")
check(sum(prev_saved$pass_prevalence_10pct) == 411L, "exactly 411 species pass pooled prevalence >=10%")

kept_species <- prev_saved$Species_full[prev_saved$pass_prevalence_10pct]
input_filtered_saved <- read.csv(input_filtered_file, check.names = FALSE)
check(
  nrow(input_filtered_saved) == 1647L &&
    ncol(input_filtered_saved) == 416L &&
    identical(input_filtered_saved$Run_ID, scores$Run_ID) &&
    identical(colnames(input_filtered_saved)[-(1:5)], kept_species),
  "prevalence-filtered pooled input preserves 1,647 Run IDs and the exact 411 species"
)
check(
  max(abs(
    as.matrix(input_filtered_saved[, -(1:5), drop = FALSE]) -
      pooled[, kept_species, drop = FALSE]
  )) < 1e-15 &&
    isTRUE(all.equal(
      input_filtered_saved[, 1:5], scores,
      tolerance = 1e-15, check.attributes = FALSE
    )),
  "prevalence-filtered pooled input preserves all tested scores and abundances"
)

cor_saved <- read.csv(cor_file, check.names = FALSE)
check(nrow(cor_saved) == 822L, "saved correlation table has 411 species x 2 axes")

score_lookup <- list(
  Production = scores$Production_sum,
  Degradation = scores$Degradation_sum
)
rho_recalc <- numeric(nrow(cor_saved))
p_recalc <- numeric(nrow(cor_saved))
for (i in seq_len(nrow(cor_saved))) {
  vals <- pooled[, cor_saved$Species_full[i]]
  tst <- suppressWarnings(
    cor.test(vals, score_lookup[[cor_saved$Axis[i]]], method = "spearman", exact = FALSE)
  )
  rho_recalc[i] <- unname(tst$estimate)
  p_recalc[i] <- tst$p.value
}
check(max(abs(rho_recalc - cor_saved$rho)) < 1e-12, "all pooled Spearman rho values independently match")
check(max(abs(p_recalc - cor_saved$p_value)) < 1e-12, "all pooled Spearman P values independently match")

q_recalc <- ave(p_recalc, cor_saved$Axis, FUN = function(x) p.adjust(x, method = "BH"))
check(max(abs(q_recalc - cor_saved$q_value)) < 1e-12, "all axis-wise BH q values independently match")

top_recalc <- cor_saved |>
  filter(rho > 0, q_value < 0.05) |>
  group_by(Axis) |>
  arrange(desc(rho), q_value, Species, .by_group = TRUE) |>
  slice_head(n = 15L) |>
  mutate(axis_rank = row_number()) |>
  ungroup()
top_saved <- read.csv(top_file, check.names = FALSE)
top_recalc_cmp <- top_recalc |>
  arrange(Axis, axis_rank) |>
  select(Axis, Species_full, axis_rank) |>
  as.data.frame()
top_saved_cmp <- top_saved |>
  arrange(Axis, axis_rank) |>
  select(Axis, Species_full, axis_rank) |>
  as.data.frame()
check(
  isTRUE(all.equal(top_recalc_cmp, top_saved_cmp, check.attributes = FALSE)),
  "Production and Degradation top-15 selections independently match"
)

plot_saved <- read.csv(plot_file, check.names = FALSE)
check(nrow(plot_saved) == 56L, "heatmap contains 28 unique species x 2 axes")
check(length(unique(plot_saved$Species_full)) == 28L, "heatmap contains 28 unique species")
check(all(is.finite(plot_saved$rho)), "all plotted heatmap values are finite")

sample_saved <- read.csv(sample_file, check.names = FALSE)
taxonomy_saved <- read.csv(taxonomy_file, check.names = FALSE)
check(identical(sample_saved$Run_ID, scores$Run_ID), "sample-level delivery table preserves exact pooled Run-ID order")
score_cols_match <- all.equal(
  sample_saved[, c("Production_sum", "Degradation_sum")],
  scores[, c("Production_sum", "Degradation_sum")],
  tolerance = 1e-15,
  check.attributes = FALSE
)
check(isTRUE(score_cols_match), "sample-level delivery table preserves exact functional scores")

abundance_ok <- TRUE
for (i in seq_len(nrow(taxonomy_saved))) {
  abundance_ok <- abundance_ok && max(abs(
    sample_saved[[taxonomy_saved$sample_table_column[i]]] -
      pooled[, taxonomy_saved$Species_full[i]]
  )) < 1e-15
}
check(abundance_ok, "sample-level delivery table preserves every selected species abundance")

counts_saved <- read.csv(count_file, check.names = FALSE)
counts_recalc <- scores |>
  count(Cohort, Analysis_Group, name = "n_samples") |>
  arrange(match(Cohort, cohorts), Analysis_Group)
check(identical(counts_saved, counts_recalc), "cohort-by-group sample counts independently match")

cancer <- read.csv(cancer_file, check.names = FALSE) |>
  filter(n_cohorts_significant >= 3L) |>
  select(Species_full, Cancer_recurrent_n = n_cohorts_significant)
healthy <- read.csv(healthy_file, check.names = FALSE) |>
  filter(n_cohorts_strict >= 3L) |>
  select(Species_full, Healthy_recurrent_n = n_cohorts_strict)
overlap_saved <- read.csv(overlap_file, check.names = FALSE)
expected_cancer <- ifelse(overlap_saved$Species_full %in% cancer$Species_full,
                          cancer$Cancer_recurrent_n[match(overlap_saved$Species_full, cancer$Species_full)], 0)
expected_healthy <- ifelse(overlap_saved$Species_full %in% healthy$Species_full,
                           healthy$Healthy_recurrent_n[match(overlap_saved$Species_full, healthy$Species_full)], 0)
check(all(overlap_saved$Cancer_recurrent_n == expected_cancer), "Cancer-enrichment overlap independently matches")
check(all(overlap_saved$Healthy_recurrent_n == expected_healthy), "Healthy-enrichment overlap independently matches")

csv_names <- c(
  "pooled_analysis_input_all_union_species.csv",
  "pooled_analysis_input_prevalence10_species.csv",
  "pooled_species_prevalence.csv",
  "pooled_species_Production_Degradation_correlations_all.csv",
  "selected_top15_per_axis.csv",
  "heatmap_plot_values_long.csv",
  "selected_species_disease_enrichment_overlap.csv",
  "selected_species_taxonomy_map.csv",
  "pooled_sample_scores_selected_species.csv",
  "sample_counts_by_cohort_group.csv"
)
copy_hash_ok <- all(vapply(csv_names, function(nm) {
  identical(
    unname(tools::md5sum(file.path(out_dir, nm))),
    unname(tools::md5sum(file.path(use_out_dir, nm)))
  )
}, logical(1)))
check(copy_hash_ok, "all ten use-data CSV copies are byte-identical to analytical outputs")

check(
  identical(unname(tools::md5sum(png_file)), unname(tools::md5sum(transport_file))),
  "analytical and PowerPoint PNG files are byte-identical"
)

png_info <- system2(
  "/usr/bin/file",
  args = shQuote(png_file),
  stdout = TRUE,
  stderr = TRUE
)
check(
  any(grepl("3800 x 4800", png_info, fixed = TRUE)) &&
    any(grepl("8-bit/color RGB", png_info, fixed = TRUE)) &&
    any(grepl("non-interlaced", png_info, fixed = TRUE)),
  "PNG is non-interlaced 8-bit RGB at 3800x4800"
)

sips_info <- system2(
  "/usr/bin/sips",
  args = c("-g", "profile", "-g", "dpiWidth", "-g", "dpiHeight", shQuote(png_file)),
  stdout = TRUE,
  stderr = TRUE
)
check(any(grepl("profile: sRGB IEC61966-2.1", sips_info, fixed = TRUE)), "PNG embeds sRGB IEC61966-2.1")
check(
  any(grepl("dpiWidth: 400.000", sips_info, fixed = TRUE)) &&
    any(grepl("dpiHeight: 400.000", sips_info, fixed = TRUE)),
  "PNG records exact 400 dpi metadata"
)

report <- c(
  "Independent verification: CRC WGS pooled Production/Degradation heatmap",
  paste0("Verified: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
  checks,
  failures,
  paste0("TOTAL_PASS\t", length(checks)),
  paste0("TOTAL_FAIL\t", length(failures))
)
writeLines(report, file.path(out_dir, "independent_verification_report.txt"))
cat(paste(report, collapse = "\n"), "\n")

if (length(failures) > 0L) stop("Independent verification failed.")
