#!/usr/bin/env Rscript
source(file.path(dirname(sub("^--file=","",commandArgs(FALSE)[grepl("^--file=",commandArgs(FALSE))])),"common.R"))
stopifnot(!file.exists(file.path(out,"resources/prepared.rds")))
checks<-list();ck<-function(name,pass,delta=NA_real_){checks[[name]]<<-data.table(check=name,pass=as.logical(pass),max_difference=delta);cat(name,pass,delta,'\n');flush.console();stopifnot(pass)}
paths<-c(prepared14=file.path(old14,"resources/allcell_prepared.rds"),groups14=file.path(old14,"results/tables/01_FROZEN_allcell_patient_scores_groups.csv"),lineages02=file.path(src,"02_lineage_reannotation/intermediate/10_lineage_pseudobulk_counts.rds"),unresolved14=file.path(old14,"results/tables/00_unresolved_immune_pseudobulk.csv.gz"),membership=member_path,exact04=file.path(src,"04_Fig7_Immune_Programs_26.09.06/resources/Fig6_exact_MSigDB_2026.1.Hs_membership.csv"),focus07=file.path(prior,"results/tables/00_prespecified_focus.csv"),plan=file.path(out,"ANALYSIS_PLAN_FROZEN.md"))
stopifnot(all(file.exists(paths)));wt(data.table(role=names(paths),path=substring(paths,nchar(src)+2),sha256=vapply(paths,sha,character(1))),"00_input_manifest.csv")
oldfiles<-list.files(old14,recursive=TRUE,full.names=TRUE);wt(data.table(path=substring(oldfiles,nchar(src)+2),sha256=vapply(oldfiles,sha,character(1))),"00_protected14_before.csv")
a<-readRDS(paths['prepared14']);md<-as.data.table(a$metadata);raw<-a$counts$All_cells;e<-a$exposure
ck('raw_dimensions',identical(dim(raw),c(24292L,15L)));ck('unique_gene_sample_patient',!anyDuplicated(rownames(raw))&&!anyDuplicated(colnames(raw))&&!anyDuplicated(md$Patient)&&!anyDuplicated(md$Sample));ck('integer_finite_nonnegative',all(is.finite(raw))&&all(raw>=0)&&all(raw==floor(raw)));ck('sample_order',identical(colnames(raw),md$Sample));ck('one_sample_per_patient',uniqueN(md$Patient)==15&&uniqueN(md$Sample)==15);ck('retained_cells',sum(md$all_cells)==91844);ck('total_UMI',sum(raw)==572043334)
pb<-readRDS(paths['lineages02']);x<-as.matrix(Reduce('+',pb));u<-fread(paths['unresolved14']);um<-as.matrix(u[,-1]);rownames(um)<-u[[1]];stopifnot(identical(colnames(um),paste0("V",1:15)));colnames(um)<-fread(paths["groups14"])$Sample # Original14 wrote this matrix in frozen md$Sample order
x<-x[rownames(raw),colnames(raw)]+um[rownames(raw),colnames(raw)];ck('independent_raw_aggregation',identical(unname(x),unname(raw)),max(abs(x-raw)))
yy<-DGEList(raw);X0<-model.matrix(reformulate(covars(md)),md);k<-filterByExpr(yy,design=X0,min.count=10,min.total.count=15,large.n=10,min.prop=.7);yy<-calcNormFactors(yy[k,,keep.lib.sizes=FALSE],method='TMM')
ck('same_gene_filter',identical(k,e$keep));ck('same_filtered_counts',all(yy$counts==e$y$counts));ck('same_library_sizes',identical(yy$samples$lib.size,e$y$samples$lib.size));ck('same_TMM',max(abs(yy$samples$norm.factors-e$y$samples$norm.factors))<1e-12,max(abs(yy$samples$norm.factors-e$y$samples$norm.factors)))
eff<-yy$samples$lib.size*yy$samples$norm.factors;xx<-log2(1+sweep(raw[c('SARDH','PIPOX'),],2,eff,'/')*1e6);zz<-t(apply(xx,1,z));D<-colMeans(zz);gp<-ifelse(D>median(D),'High','Low')
ck('score_matches14',max(abs(D-md$degradation_mean_z))<1e-12,max(abs(D-md$degradation_mean_z)));ck('same_frozen_groups',all(gp==md$group));ck('group_counts',sum(gp=='High')==7&&sum(gp=='Low')==8);ck('pre_all_low',all(md[treatment=='Pre',group]=='Low'));ck('post_group_counts',nrow(md[treatment=='Post'])==12&&sum(md[treatment=='Post',group]=='High')==7)
csv<-fread(paths['groups14']);ck('frozen_csv_labels',identical(csv$Patient,md$Patient)&&identical(csv$group,md$group));ck('frozen_csv_scores',max(abs(csv$degradation_mean_z-md$degradation_mean_z))<1e-12)
md[,group:=factor(group,levels=c('Low','High'))];spec<-list(post_group=c('histology','group'),post_continuous=c('histology','exposure_z'),all_group=c('treatment','histology','group'),all_continuous=c('treatment','histology','exposure_z'))
for(sc in names(spec)){dt<-copy(md);if(startsWith(sc,'post'))dt<-dt[treatment=='Post'];X<-model.matrix(reformulate(spec[[sc]]),dt);ck(paste0(sc,'_design'),qr(X)$rank==ncol(X)&&nrow(X)-ncol(X)>=5&&min(table(dt$group))>=3)}
m<-as.data.table(readRDS(member_path));ck('database_version',all(m$db_version=='2026.1.Hs'));sets<-lapply(split(m$gene_symbol,m$pathway),unique);old<-fread(paths['exact04']);ck('exact_pathway_ID_membership',all(vapply(focus$pathway[1:4],function(id)setequal(sets[[id]],old[gs_name==id,gene_symbol]),logical(1))))
wt(md,'01_frozen_patient_groups.csv');wt(focus,'00_focus.csv');wt(data.table(gene=rownames(raw),retained=k),'01_gene_filter.csv');wt(data.table(gene=rownames(raw),raw),'01_allcell_raw_UMI_pseudobulk.csv.gz')
saveRDS(list(metadata=md,y=e$y,raw=raw),file.path(out,'resources/prepared.rds'))
wt(rbindlist(checks),'01_preflight_checks.csv');writeLines(sha(file.path(out,'ANALYSIS_PLAN_FROZEN.md')),file.path(out,'logs/plan_sha256.txt'));capture.output(sessionInfo(),file=file.path(out,'logs/sessionInfo_prepare.txt'))
cat('PREFLIGHT PASS:',length(checks),'checks; retained genes',nrow(yy),'\n');print(md[,.(Patient,treatment,histology,all_cells,group,degradation_mean_z)])
