#!/usr/bin/env Rscript
source(file.path(dirname(sub("^--file=","",commandArgs(FALSE)[grepl("^--file=",commandArgs(FALSE))])),"common.R"))
fc<-file.path(tempdir(),'font_cache');dir.create(fc,showWarnings=FALSE);Sys.setenv(XDG_CACHE_HOME=fc)
suppressPackageStartupMessages({library(ggplot2);library(patchwork);library(stringr)})
stopifnot(all(fread(file.path(out,'results/tables/03_numerical_verification.csv'))$pass))
hi<-'#BC496B';lo<-'#327F94';ink<-'#223543';gray<-'#65737D'
fmt<-function(x)ifelse(is.na(x),'NE',ifelse(x<.001,formatC(x,format='e',digits=1),formatC(x,format='f',digits=3)))
base<-theme_classic(base_size=11,base_family='Arial')+theme(axis.text=element_text(colour=ink),axis.title=element_text(colour=ink),plot.title=element_text(face='bold',colour=ink,size=15),plot.subtitle=element_text(size=10.5,colour=gray,lineheight=1.15),plot.caption=element_text(size=9,colour=gray,hjust=0,lineheight=1.2),legend.position='bottom',legend.title=element_text(size=10),legend.text=element_text(size=9.5),plot.margin=margin(10,15,10,10))
savefig<-function(p,n,w,h){ggsave(file.path(out,'results/figures',paste0(n,'.png')),p,width=w,height=h,dpi=600,device=ragg::agg_png,bg='white');ggsave(file.path(out,'results/figures',paste0(n,'.pdf')),p,width=w,height=h,device=cairo_pdf,bg='white');ggsave(file.path(out,'results/figures',paste0(n,'.svg')),p,width=w,height=h,device=grDevices::svg,bg='white');cat('SAVED',n,w,h,'\n')}
d<-fread(file.path(out,'results/tables/plotdata_Fig8e_GO_overview.csv'));counts<-fread(file.path(out,'results/tables/03_GO_display_counts.csv'));allg<-fread(file.path(out,'results/tables/02_GSEA_all_scopes.csv'));family_n<-allg[scope=='post_group',.N]
label<-function(x){s<-str_to_sentence(gsub('_',' ',sub('^GOBP_','',x)));s<-gsub('\\bDna\\b|\\bdna\\b','DNA',s);s<-gsub('\\brna\\b','RNA',s);str_wrap(s,width=34)}
d[,':='(display_label=label(pathway),neglog10q=-log10(q_global),absNES=abs(NES))]
qmax<-if(nrow(d))ceiling(max(d$neglog10q)) else 2; xmax<-if(nrow(d))ceiling(max(d$absNES)*2)/2+.15 else 3
sb<-if(nrow(d))unique(floor(seq(min(d$leading_edge_n),max(d$leading_edge_n),length.out=3)/5)*5) else c(5,10,20);sb<-sb[sb>0];sizelim<-if(nrow(d))c(0,max(d$leading_edge_n)) else c(0,20)
parts<-lapply(c('High','Low'),function(dr){dd<-copy(d[direction==dr]);setorder(dd,display_order);dd[,term:=factor(pathway,levels=rev(pathway))];col<-if(dr=='High')hi else lo
 if(!nrow(dd))return(ggplot()+annotate('text',x=0,y=0,label='No GO:BP terms meet\nglobal BH q < 0.05',family='Arial',colour=gray,size=4)+theme_void()+labs(title=paste0('Degradation-',dr))+theme(plot.title=element_text(family='Arial',face='bold',colour=col,size=15),plot.margin=margin(10,15,10,10)))
 ggplot(dd,aes(x=absNES,y=term))+geom_segment(aes(x=0,xend=absNES,yend=term),colour='#DCE5EB',linewidth=.6)+geom_point(aes(fill=neglog10q,size=leading_edge_n),shape=21,colour='white',stroke=.45)+scale_y_discrete(labels=setNames(dd$display_label,dd$pathway),expand=expansion(add=.62))+scale_x_continuous(limits=c(0,xmax),breaks=seq(0,floor(xmax),1),expand=expansion(mult=c(0,.04)))+scale_fill_gradientn(colours=c('#D3E6EA','#62A7BA','#286886','#182E52'),limits=c(0,qmax),name='−log10(global BH q)',guide=guide_colorbar(order=1,barwidth=unit(35,'mm'),barheight=unit(2.5,'mm')))+scale_size_area(max_size=6,limits=sizelim,breaks=sb,name='Leading-edge genes',guide=guide_legend(order=2,override.aes=list(fill='#608A9F',colour='white')))+labs(title=paste0('Degradation-',dr),subtitle=if(dr=='High')'Enriched toward higher degradation expression' else 'Enriched toward lower degradation expression',x='Enrichment strength |NES|',y=NULL)+base+theme(axis.line.y=element_blank(),axis.ticks.y=element_blank(),axis.text.y=element_text(size=10.5,lineheight=1.03,margin=margin(r=9)),axis.line.x=element_line(colour='#9FAAB1',linewidth=.35),axis.ticks.x=element_line(colour='#9FAAB1'),plot.title=element_text(colour=col,size=15),legend.margin=margin(4,6,4,6))})
p<-(parts[[1]]|parts[[2]])+plot_layout(guides='collect')+plot_annotation(title='Whole-tumour pathways by sarcosine-degradation expression',subtitle='Patient-level pseudobulk  |  Post-treatment NSCLC  |  High n = 7, Low n = 5',caption=paste0('Histology-adjusted GSEA; global BH correction across ',format(family_n,big.mark=','),' tested gene sets.\nUp to eight significant GO:BP terms per direction, with gene-overlap filtering for display. Whole-tissue associations may reflect cell composition.'),theme=theme(plot.title=element_text(family='Arial',face='bold',size=17,colour=ink),plot.subtitle=element_text(family='Arial',size=11,colour=gray,margin=margin(t=5,b=8)),plot.caption=element_text(family='Arial',size=9,colour=gray,hjust=0,lineheight=1.15,margin=margin(t=8)),plot.margin=margin(14,16,12,16)))&theme(legend.position='bottom')
savefig(p,'Fig8e_AllCell_Degradation_GO_Overview',12.4,7.1);wt(d,'plotdata_Fig8e_GO_overview.csv')
# Companion exposes patient distributions and independent testing limits for all four exact programs.
e<-fread(file.path(out,'results/tables/plotdata_Fig8e_Exact_Fig7_Pathways.csv'));v<-fread(file.path(out,'results/tables/04_patient_score_values.csv'))[scope=='post_group'];v[,group:=factor(group,levels=c('Low','High'))]
labels<-c('APC cross-presentation','TCR signaling','TNFR2-related noncanonical NF-κB','IFN-γ response')
pp<-lapply(seq_len(4),function(i){id<-focus$pathway[i];z<-e[pathway==id];dd<-v[pathway==id]
 ggplot(dd,aes(group,score,colour=group))+geom_hline(yintercept=0,colour='#DFE5E8',linewidth=.45)+geom_point(position=position_jitter(width=.075,height=0,seed=260914+i),size=2.8,alpha=.95)+stat_summary(fun=median,geom='crossbar',width=.35,colour=ink,linewidth=.4)+scale_colour_manual(values=c(Low=lo,High=hi),guide='none')+scale_x_discrete(labels=c('Low\nn = 5','High\nn = 7'))+scale_y_continuous(expand=expansion(mult=c(.12,.15)))+labs(title=labels[i],subtitle=paste0('GSEA NES = ',sprintf('%.2f',z$NES),'  |  global q = ',fmt(z$q_global),'\nCAMERA global q = ',fmt(z$CAMERA_q)),x=NULL,y='Patient pathway score (standardized)',caption=paste0('Adjusted High − Low: ',sprintf('%.2f',z$score_beta),' [',sprintf('%.2f',z$score_ci_low),', ',sprintf('%.2f',z$score_ci_high),']\n95% HC3 interval; score BH q = ',fmt(z$score_q)))+base+theme(plot.title=element_text(size=13),axis.title.y=element_text(size=10),plot.margin=margin(10,22,12,12))})
p2<-wrap_plots(pp,ncol=2)+plot_annotation(title='The four Figure 7 immune programs in whole-tumour RNA',subtitle='Same fixed patient groups  |  Post-treatment NSCLC  |  Histology-adjusted comparisons',caption='Each point is one patient. Bars show unadjusted medians; effects and intervals come from the adjusted model.\nGSEA, CAMERA and patient-score tests address different hypotheses. Enrichment does not establish a sequential mechanism.',theme=theme(plot.title=element_text(family='Arial',face='bold',size=17,colour=ink),plot.subtitle=element_text(family='Arial',size=11,colour=gray,margin=margin(t=5,b=6)),plot.caption=element_text(family='Arial',size=9,colour=gray,hjust=0,lineheight=1.15),plot.margin=margin(14,16,12,16)))
savefig(p2,'Fig8e_Exact_Fig7_Pathway_Checks',10.6,8.5)
wt(v,'plotdata_Fig8e_Exact_Patient_Scores.csv');capture.output(sessionInfo(),file=file.path(out,'logs/sessionInfo_plot.txt'))
